export { default as HeroSection } from "./HeroSection"
export { default as ServicesSection } from "./ServicesSection"
export { default as ProcessSection } from "./ProcessSection"
export { default as TestimonialsSection } from "./TestimonialsSection"
export { default as FAQSection } from "./FAQSection"
export { default as CTASection } from "./CTASection"
